### ISSUE TITLE
can this run on ubuntu 14.04.5 server amd64

### ISSUE THREAD

**Issue by csrgxtu** [cnplab/cdnsim#1]
i was wondering if this repo can easily install on ubuntu 14.04.5 server amd64, and how to run a demo.

**Comment by an0xeb** [comment]
hi @csrgxtu  yes, any system with Python version 2.7 will be okay. Jest follow the steps given [here](https://github.com/cnplab/cdnsim#what-you-need-to-run-cdnsim)

**Comment by edudrm** [comment]
-geo - county codes (e.g., 'de' or 'fr,de'). Files should be stored in 'geoAS' directory (examples provided). Geographical data can be obtained from here.

This part does not work anymore. So the project.
